name: neuroccm
favicon: null
layout_spectrum: 0.74556
typography_spectrum: 0.24827
title: neuroccm - Houman Khosravani
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#27200e'
    - '#a09955'
    - '#005739'
    - '#4bffff'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
