name: neuroccm
favicon: null
layout_spectrum: 0.5769407264888287
typography_spectrum: 0.3833032266702503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07182287122122943
  lightness: 0.8011942317243665
  saturation: 0.5338262219447643
  rhythmicContrast: 0.8774040802381933
purpose: []
